config/routes.rb
Rails.application.routes.draw do
  root			'static_pages#home'
  get 'home'	=> 	'static_pages#home'
  resources :catalogs do
  	resources :topics
  end
end

app/models/catalog.rb
class Catalog < ActiveRecord::Base
  has_many :topics, :foreign_key => "game_name", :class_name => "Topic", dependent: :destroy
  before_save {self.game_name, = game_name.downcase}
  validates :game_name, presence: true, length: { maximum: 20 },
			uniqueness: {case_sensitive: false }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :topic
end

app/models/topic.rb
class Topic < ActiveRecord::Base
has_many :comments, :foreign_key => "topic_id", :class_name => "Comment", dependent: :destroy


  belongs_to :catalog 

  validates :title, presence: true
  validates :title, length: {minimum: 2}
  validates :title, length: {maximum: 140}
  
  validates :handle, presence: true
  validates :handle, length: {in: 1..20}
  validates :handle, uniqueness: true

  validates :game_name, presence: true
  validates :game_name, length: {minimum: 0}
  validates :game_name, length: {maximum: 20}

  validates :description, presence: true
  validates :description,length: {minimum: 0}
  validates :description, length: {maximum: 150}

end

app/controllers/catalogs_controller.rb
class CatalogsController < ApplicationController
  def show
    @catalog = Catalog.find(params[:id])
    @topics = Topic.where(game_name: @catalog.id)
    @topic = @catalog.topics.build
  end

  def create
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
def new
end

def create

end

def show
end


def edit

end

def update

end

def destroy
end





end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @catalogs = Catalog.all
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
	
  def show
    @topic = Topic.find(params[:id])
    @comments = Comment.all(params[@topic_id])
  end
  
  def new
    @topic = Topic.new
  end

  def create
    @catalog = Catalog.find(params[:catalog_id])
    @topic = @catalog.topics.create!(topic_params)
    if @topic.save
      redirect_to @catalog
    else
    end
	end

  def update
  end

  def edit
  end 

  def destroy
  end

  private

    def topic_params
      params.require(:topic).permit(:title, :description, :handle)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Team Finder"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/catalog_helper.rb
module CatalogHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/catalogs/create.html.erb
<h1>Catalog#create</h1>
<p>Find me in app/views/catalog/create.html.erb</p>

app/views/catalogs/index.html.erb
<h1>Catalog#index</h1>
<p>Find me in app/views/catalog/index.html.erb</p>

app/views/catalogs/show.html.erb
<%provide(:title, @catalog.catalog_name)%>
<div class="center jumbotron other-color">
  <h1><%=@catalog.catalog_name %></h1>


  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for [@catalog, Topic.new] do |f| %>
        <%= render 'shared/error_messages' %>

        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %><br />

        <%= f.label :handle %>
        <%= f.text_field :handle, class: 'form-control' %><br />
  
        <%= f.label :description %>
        <%= f.text_field :description, class: 'form-control' %><br />

        <%= f.hidden_field(:game_name, :value => @catalog.game_name) %>

        <%= f.submit "Create New Topic", class: "btn btn-primary"%>
      <% end %>
    </div>
  </div>
</div>

<div class="center container">
  <div class="row">
    <% @topics.each do |topic| %>
      <div class="jumbotron col-md-3">
          <p>
  	    "<%= topic.title %>"<br />
        <%= topic.handle%><br />
        <%= topic.description %>
  	  </p>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Developed by <a href="https://github.com/philsher93/">Phillip Sheridan</a> 
    and <a href="https://github.com/wisard1862/">Daniel Swain Jr</a>
  </small>
</footer>

app/views/layouts/_header.html.erb
  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <%= link_to "Team Finder", root_path, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", home_path %></li>
          <li><a href="https://github.com/philsher93/teamdota">Github</a></li>
        </ul>
      </nav>
    </div>
  </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css" rel="stylesheet">
  <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @topic.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@topic.errors.count, "error") %>.
    </div>
    <ul>
    <% @topic.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<%provide(:title, "Home") %>
<div class="center jumbotron other-color">
  <h1>Welcome to Team Finder</h1>
  <p>
    Team Finder is a bulletin board for finding members of your gameplay caliber to fill out your team in MOBA games. Find members, friends, clans, or whatever your team finding needs are for games like Dota 2, League of Legends, Heroes of the Storm, etc. Check out the available catalogs and filter through some topics to find the team for you! 
  </p>
</div>

<div class="center jumbotron other-color">
  <h2>Current Catalogs</h2>
  <div class="row">
    <% @catalogs.each do |catalog| %>
    <div class="col-md-4">
      <%= link_to catalog.catalog_name, catalog_path(catalog.id)  %>
    </div> 
    <% end %>
  </div>

</div>
<%= link_to image_tag("dota2logo.png", alt: "Dota2 Logo", height: '32', width: '32'),
	'http://blog.dota2.com/' %>
  <%= link_to image_tag("league_logo-bfd94f798b1abfe6a036242419b3748b.png", alt: "League of Legends Logo", height: '32', width: '32'),
  'http://leagueoflegends.com/' %>
  <%= link_to image_tag("Heroes_Of_The_Storm_138203755237651.jpg", alt: "Heros of the Storm Logo", height: '32', width: '32'),
  'http://us.battle.net/heroes/en/' %>
  <%= link_to image_tag("smite Logo.png", alt: "Smite Logo", height: '32', width: '32'),
  'http://www.hirezstudios.com/smite/' %>
  <%= link_to image_tag("647225de-1a33-4385-b8d4-30f24cf97b53.png", alt: "Heroes of Newerth Logo", height: '32', width: '32'),
  'http://www.heroesofnewerth.com' %>

app/views/topics/create.html.erb
<div>you did something!</div>

app/views/topics/delete.html.erb
<h1>Topics#delete</h1>
<p>Find me in app/views/topics/delete.html.erb</p>

app/views/topics/show.html.erb
<%provide(:title, @topic.title)%>